#!/usr/bin/env bash

mkdir -p psalms

for ((i=1; i<=150; i++))
do
	filename="$(printf "%03d" $i).yaml"
	touch "psalms/$filename"
done

for ((i=20; i<=150; i++))
do
	filename="$(printf "%03d" $i).yaml"
	rm "psalms/$filename"
done
